server:
  port: 8079

jwt:
  expiration-ms: 604800000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_distribution?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200313
