spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_distribution?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200313
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      # 基于服务发现自动路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: agent-route
          uri: lb://agent-service
          predicates:
            - Path=/agent/**
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: commission-route
          uri: lb://commission-service
          predicates:
            - Path=/commission/**
jwt:
  whitelist:
    paths:
      - /auth/**
      - /public/**
